# Install Required Libraries

In [1]:
!pip install scikit-learn gensim nltk pandas


[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# Example Dataset

In [2]:
documents = [
    "machine learning is fascinating",
    "deep learning drives artificial intelligence",
    "machine learning and deep learning are powerful",
    "artificial intelligence is the future"
]

# Text Processing

In [3]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')

tokenized_docs = [word_tokenize(doc.lower()) for doc in documents]
print(tokenized_docs)

[['machine', 'learning', 'is', 'fascinating'], ['deep', 'learning', 'drives', 'artificial', 'intelligence'], ['machine', 'learning', 'and', 'deep', 'learning', 'are', 'powerful'], ['artificial', 'intelligence', 'is', 'the', 'future']]


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\aayus\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# Bag of Words

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

bow_matrix = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", bow_matrix.toarray())

Vocabulary: ['and' 'are' 'artificial' 'deep' 'drives' 'fascinating' 'future'
 'intelligence' 'is' 'learning' 'machine' 'powerful' 'the']
BoW Matrix:
 [[0 0 0 0 0 1 0 0 1 1 1 0 0]
 [0 0 1 1 1 0 0 1 0 1 0 0 0]
 [1 1 0 1 0 0 0 0 0 2 1 1 0]
 [0 0 1 0 0 0 1 1 1 0 0 0 1]]


# Normalized Count Occurrence

In [5]:
import numpy as np

bow = bow_matrix.toarray()

normalized_bow = bow / bow.sum(axis=1, keepdims=True)

print("Normalized BoW:\n", normalized_bow)

Normalized BoW:
 [[0.         0.         0.         0.         0.         0.25
  0.         0.         0.25       0.25       0.25       0.
  0.        ]
 [0.         0.         0.2        0.2        0.2        0.
  0.         0.2        0.         0.2        0.         0.
  0.        ]
 [0.14285714 0.14285714 0.         0.14285714 0.         0.
  0.         0.         0.         0.28571429 0.14285714 0.14285714
  0.        ]
 [0.         0.         0.2        0.         0.         0.
  0.2        0.2        0.2        0.         0.         0.
  0.2       ]]


# TF-IDF Representation

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("TF-IDF Vocabulary:", tfidf_vectorizer.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())

TF-IDF Vocabulary: ['and' 'are' 'artificial' 'deep' 'drives' 'fascinating' 'future'
 'intelligence' 'is' 'learning' 'machine' 'powerful' 'the']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.         0.61422608
  0.         0.         0.4842629  0.39205255 0.4842629  0.
  0.        ]
 [0.         0.         0.43584673 0.43584673 0.55281632 0.
  0.         0.43584673 0.         0.35285549 0.         0.
  0.        ]
 [0.41264483 0.41264483 0.         0.32533392 0.         0.
  0.         0.         0.         0.5267717  0.32533392 0.41264483
  0.        ]
 [0.         0.         0.40104275 0.         0.         0.
  0.50867187 0.40104275 0.40104275 0.         0.         0.
  0.50867187]]


# Word Embeddings using Word2Vec (gensim)

In [7]:
from gensim.models import Word2Vec

model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)

# Get Word Embedding Vector

In [8]:
vector = model.wv['learning']

print("Word2Vec embedding for 'learning':\n", vector)

Word2Vec embedding for 'learning':
 [-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.

# Find Similar Words

In [9]:
model.wv.most_similar('learning')

[('are', 0.216176375746727),
 ('fascinating', 0.0931011214852333),
 ('the', 0.09291683882474899),
 ('drives', 0.07963486760854721),
 ('and', 0.06285078823566437),
 ('powerful', 0.027063529938459396),
 ('future', 0.016134677454829216),
 ('intelligence', -0.01083916611969471),
 ('is', -0.027750369161367416),
 ('artificial', -0.05234673246741295)]